BLFS: It don't depend on DocBook-XSL for now.

diff --git a/blfs-tool b/blfs-tool
--- a/blfs-tool
+++ b/blfs-tool
@@ -129,12 +129,12 @@ else
   exit 2
 fi
 
-if `echo $XML_FILE | xsltproc --noout - 2>/dev/null` ; then
-  check_version "1.69.1" "1.69.1" "DocBook XSL"
-else
-  echo "Warning: not found a working DocBook XSL 1.69.1 installation"
-  exit 2
-fi
+# if `echo $XML_FILE | xsltproc --noout - 2>/dev/null` ; then
+#   check_version "1.69.1" "1.69.1" "DocBook XSL"
+# else
+#   echo "Warning: not found a working DocBook XSL 1.69.1 installation"
+#   exit 2
+# fi
 
 echo "${SD_BORDER}${nl_}"
 
