corrected traces in download function, was showing false failures

diff --git a/common/common-functions b/common/common-functions
--- a/common/common-functions
+++ b/common/common-functions
@@ -689,13 +689,11 @@ get_sources() {              # Download file, write name to MISSING_FILES.DMP if
       set -e
 
       if [ ! -f $FILE ] ; then
-        wget $URL1 || wget $URL2 || \
-        echo "${RED}$FILE not found on the servers${OFF}"
-        echo "$FILE not found on the servers" >> MISSING_FILES.DMP
+        wget $URL1 || wget $URL2 || (echo "${RED}$FILE not found on the servers${OFF}" &&
+                                     echo "$FILE not found on the servers 1" >> MISSING_FILES.DMP )
       elif [[ "$NOMD5" != "1" ]] && ! echo "$MD5" | md5sum -c - ; then
-        wget -N $URL1 || wget -N $URL2 || \
-        echo "${RED}$FILE not found on the servers${OFF}"
-        echo "$FILE not found on the servers" >> MISSING_FILES.DMP
+        wget -N $URL1 || wget -N $URL2 || ( echo "${RED}$FILE not found on the servers${OFF}" &&
+                                            echo "$FILE not found on the servers 2" >> MISSING_FILES.DMP )
       fi
 
       if [[ "$NOMD5" != "1" ]] && ! echo "$MD5" | md5sum -c - ; then
