Text changes only

diff --git a/common/common-functions b/common/common-functions
--- a/common/common-functions
+++ b/common/common-functions
@@ -47,8 +47,8 @@ ${BOLD}  -h, --help${OFF}
 ${BOLD}  -V, --version${OFF}
         print version number, then exit
 ${BOLD}  -d  --directory DIR${OFF}
-        use DIR directory for building HLFS; all files jhahlfs produces will be
-        in the directory DIR/jhahlfs. Default is \"/mnt/lfs\".
+        use DIR directory for building ${BOLD}$(echo $PROGNAME | tr [a-z] [A-Z])${OFF}; all files jhahlfs produces will be
+        in the directory DIR/jhahlfs.
 ${BOLD}  --rebuild${OFF}
         clean the build directory before to perfom any other task. The directory
         is cleaned only if it was populated by a previous jhahlfs run.
@@ -60,13 +60,13 @@ ${BOLD}  -D, --download-client CLIENT
         use CLIENT as the program for retrieving packages (use in conjunction with -P)
 ${BOLD}  -W, --working-copy DIR${OFF}
         use the local working copy placed in DIR as the HLFS book
-${BOLD}  -L, --HLFS-version VER${OFF}
+${BOLD}  -L, --LFS-version VER${OFF}
         checkout VER version of the HLFS book. Supported versions at this time are:
-        dev* | trunk | SVN     aliases for Development HLFS
-        alpha*                 aliases for the alphabetical branch
-        udev*                  aliases for the udev_update branch
+        dev* | trunk | SVN     aliases for Development {C,H,B}LFS
+        alpha*                 aliases for the LFS alphabetical branch
+        udev*                  aliases for the LFS udev_update branch
 ${BOLD}  --fstab FILE${OFF}
-        use FILE as the /etc/fstab file for the HLFS system. If not specified,
+        use FILE as the /etc/fstab file for the ${BOLD}$(echo $PROGNAME | tr [a-z] [A-Z])${OFF}system. If not specified,
         a default /etc/fstab file with dummy values is created.
 ${BOLD}  -C, --kernel-config FILE${OFF}
         use the kernel configuration file specified in FILE to build the kernel.
@@ -104,7 +104,6 @@ ${BOLD}  -D, --dependencies  TYPE${OFF}
         If not set, both required a recommended are used.
 
                   Possible values are:
-
         required               only required dependecies are used
         recommended            both required a recommended dependencies are used
         optional               all dependencies are used
@@ -156,7 +155,7 @@ echo \"\$help\" >&2
 exit 1"
 
 no_dl_client="\
-echo \"Could not find a way to download the CLFS sources.\" >&2
+echo \"Could not find a way to download the ${BOLD}$(echo $PROGNAME | tr [a-z] [A-Z])${OFF} sources.\" >&2
 echo \"Attempting to continue.\" >&2"
 
 HEADER="# This file is automatically generated by jhalfs
