Merged r3043:3145 from experimental: New Makefile code and other improvements.

diff --git a/common/common-functions b/common/common-functions
--- a/common/common-functions
+++ b/common/common-functions
@@ -29,51 +29,15 @@ HEADER="# This file is automatically generated by jhalfs
 # Generated on `date \"+%F %X %Z\"`"
 
 
+#------------------------------------------------------#
+#        NEW Makefile scripting functions              #
+#------------------------------------------------------#
 
+
+unset get_package_tarball_name
 #----------------------------------#
-wrt_target() {                     # Create target and initialize log file
+get_package_tarball_name() {       #
 #----------------------------------#
-  local i=$1
-  local PREV=$2
-  case $i in
-    iteration* ) local LOGFILE=$this_script.log ;;
-             * ) local LOGFILE=$this_script ;;
-  esac
-(
-cat << EOF
-
-$i:  $PREV
-	@\$(call echo_message, Building)
-	@./progress_bar.sh \$@ \$\$PPID &
-	@echo -e "\n\`date\`\n\nKB: \`du -skx --exclude=${SCRIPT_ROOT} \$(MOUNT_PT)\`\n" >logs/$LOGFILE
-EOF
-) >> $MKFILE.tmp
-}
-
-
-#----------------------------------#
-wrt_target_boot() {                # Create target and initialize log file
-#----------------------------------#
-  local i=$1
-  local PREV=$2
-  case $i in
-    iteration* ) local LOGFILE=$this_script.log ;;
-             * ) local LOGFILE=$this_script ;;
-  esac
-(
-cat << EOF
-
-$i:  $PREV
-	@\$(call echo_message, Building)
-	@./progress_bar.sh \$@ \$\$PPID &
-	@echo -e "\n\`date\`\n\nKB: \`du -skx --exclude=${SCRIPT_ROOT}\`\n" >logs/$LOGFILE
-EOF
-) >> $MKFILE.tmp
-}
-
-#----------------------------#
-get_package_tarball_name() { #
-#----------------------------#
   local script_name=$1
 
    # The use of 'head' is necessary to limit the return value to the FIRST match..
@@ -88,87 +52,49 @@ get_package_tarball_name() { #
 }
 
 
+unset wrt_RunaAsRoot
 #----------------------------------#
-wrt_test_log() {                   # Initialize testsuite log file
+wrt_RunAsRoot() {                  # Some scripts must be run as root..
 #----------------------------------#
-  local TESTLOGFILE=$1
-(
-cat  << EOF
-	@echo "export TEST_LOG=$TESTLOGDIR/$TESTLOGFILE" >> envars && \\
-	su - \$(LUSER) -c "echo -e '\n\`date\`\n' >$TESTLOGDIR/$TESTLOGFILE"
-EOF
-) >> $MKFILE.tmp
-}
+  local ENV_MOUNT
+  local this_script=$1
+  local file=$2
 
-#----------------------------------#
-wrt_test_log2() {                  #
-#----------------------------------#
-  local TESTLOGFILE=$1
-(
-cat  << EOF
-	@echo "export TEST_LOG=/$SCRIPT_ROOT/test-logs/$TESTLOGFILE" >> envars && \\
-	echo -e "\n\`date\`\n" >test-logs/$TESTLOGFILE
-EOF
-) >> $MKFILE.tmp
-}
+  case ${PROGNAME} in
+    lfs   ) MOUNT_ENV="LFS" ;;
+    blfs  ) MOUNT_ENV="BLFS" ;;
+    clfs  ) MOUNT_ENV="CLFS" ;;
+    clfs2 ) MOUNT_ENV="CLFS" ;;
+    hlfs  ) MOUNT_ENV="HLFS" ;;
+    *) echo "undefined progname $PROGNAME"; exit 1 ;;
+  esac
 
-#----------------------------------#
-wrt_target_vars() {                # Target vars for hlfs (cross-build method)
-#----------------------------------#
-(
-cat  << EOF
-	@echo "export target=$(uname -m)-${TARGET}" >> envars && \\
-	echo "export ldso=/lib/${LOADER}" >> envars
-EOF
-) >> $MKFILE.tmp
-
-}
-
-
-#----------------------------------#
-wrt_copy_fstab() {                 #
-#----------------------------------#
-  local i=$1
-(
-    cat << EOF
-	@cp -v $FSTAB \$(MOUNT_PT)/etc/fstab >>logs/$i 2>&1
-EOF
-) >> $MKFILE.tmp
-}
-
-
-#----------------------------------#
-wrt_copy_fstab2() {                #
-#----------------------------------#
-  local i=$1
-(
-    cat << EOF
-	@cp -v /sources/fstab /etc/fstab >>logs/$i 2>&1
-EOF
-) >> $MKFILE.tmp
-}
-
-
-#----------------------------------#
-wrt_report() {                     #
-#----------------------------------#
 (
 cat << EOF
-
-create-sbu_du-report:  $PREV
-	@\$(call echo_message, Building)
-	@./create-sbu_du-report.sh logs $VERSION
-	@\$(call echo_report,$VERSION-SBU_DU-$(date --iso-8601).report)
-	@touch  \$@
+	@( time { export ${MOUNT_ENV}=\$(MOUNT_PT) && ${PROGNAME}-commands/`dirname $file`/\$@ >>logs/\$@ 2>&1 ; } ) 2>>logs/\$@ && \\
+	\$(PRT_DU_CR) >>logs/\$@
 EOF
 ) >> $MKFILE.tmp
-
-chapter789="$chapter789 create-sbu_du-report"
 }
 
-unset wrt_unpack
+
+#------------------------------------------------------#
+#------------------------------------------------------#
+
 #----------------------------------#
-wrt_unpack() {                     # Unpack and set 'ROOT' var
+ROOT_RunAsRoot() {                 #
+#----------------------------------#
+  local file=$1
+(
+cat << EOF
+	@( time { source envars && \$(CMDSDIR)/$file >>logs/$this_script 2>&1 ; } ) 2>>logs/$this_script && \\
+	\$(PRT_DU_CR) >>logs/$this_script
+EOF
+) >> $MKFILE.tmp
+}
+
+#----------------------------------#
+ROOT_Unpack() {                    #  An alias, for clairity
 #----------------------------------#
   local FILE=$1
   local optSAVE_PREVIOUS=$2
@@ -184,36 +110,130 @@ EOF
 (
 cat << EOF
 	@\$(call unpack,$FILE)
-	@\$(call get_pkg_root)
+	@\$(call get_pkg_root_LUSER)
 EOF
 ) >> $MKFILE.tmp
-
 }
 
-unset wrt_unpack2
+#------------------------------------------------------#
+#------------------------------------------------------#
+
 #----------------------------------#
-wrt_unpack2() {                    #
+LUSER_wrt_target() {               # Create target and initialize log file
+#----------------------------------#
+  local i=$1
+  local PREV=$2
+(
+cat << EOF
+
+$i:  $PREV
+	@\$(call echo_message, Building)
+	@./progress_bar.sh \$@ \$\$PPID &
+	@echo -e "\n\`date\`\n\nKB: \`du -skx --exclude=\$(SCRIPT_ROOT) \$(MOUNT_PT)\`\n" >logs/\$@
+EOF
+) >> $MKFILE.tmp
+}
+
+
+#----------------------------------#
+LUSER_wrt_RunAsUser() {            # Execute script inside time { }, footer to log file
+#----------------------------------#
+  local file=$1
+
+(
+cat << EOF
+	@( time { source ~/.bashrc && \$(CMDSDIR)/`dirname $file`/\$@ >> logs/\$@ 2>&1; } ) 2>> logs/\$@ && \\
+	\$(PRT_DU) >> logs/\$@
+EOF
+) >> $MKFILE.tmp
+}
+
+
+#----------------------------------#
+LUSER_wrt_unpack() {               # Unpack and set 'ROOT' var
 #----------------------------------#
   local FILE=$1
   local optSAVE_PREVIOUS=$2
 
-  if [ "${optSAVE_PREVIOUS}" != "1" ]; then
+  if [[ "${optSAVE_PREVIOUS}" != "1" ]]; then
 (
 cat << EOF
 	@\$(call remove_existing_dirs,$FILE)
 EOF
 ) >> $MKFILE.tmp
   fi
+
 (
-cat  << EOF
-	@\$(call unpack2,$FILE)
-	@\$(call get_pkg_root,nouser)
+cat << EOF
+	@\$(call unpack,$FILE)
+	@\$(call get_pkg_root_LUSER)
+EOF
+) >> $MKFILE.tmp
+
+}
+
+
+#----------------------------------#
+LUSER_wrt_CopyFstab() {            #
+#----------------------------------#
+(
+cat << EOF
+	@( time { cp -v \$(MOUNT_PT)/sources/fstab \$(MOUNT_PT)/etc/fstab >>logs/\$@ 2>&1 ; } ) 2>>logs/\$@
 EOF
 ) >> $MKFILE.tmp
 }
 
+
 #----------------------------------#
-wrt_unpack3() {                    #
+LUSER_wrt_test_log() {             # Initialize testsuite log file
+#----------------------------------#
+  local TESTLOGFILE=$1
+(
+cat  << EOF
+	@echo "export  TEST_LOG=$TESTLOGDIR/$TESTLOGFILE" >> envars && \\
+	echo -e '\n\`date\`\n' >$TESTLOGDIR/$TESTLOGFILE
+EOF
+) >> $MKFILE.tmp
+}
+
+
+#----------------------------------#
+LUSER_RemoveBuildDirs() {          #
+#----------------------------------#
+  local name=$1
+(
+cat << EOF
+	@\$(call remove_build_dirs,$name)
+EOF
+) >> $MKFILE.tmp
+}
+
+#-----------------------------------------------------------------#
+#-----------------------------------------------------------------#
+
+#----------------------------------#
+CHROOT_wrt_target() {              # Create target and initialize log file
+#----------------------------------#
+  local i=$1
+  local PREV=$2
+  case $i in
+    iteration* ) local LOGFILE="${this_script}.log" ;;
+             * ) local LOGFILE="${this_script}"      ;;
+  esac
+(
+cat << EOF
+
+$i:  $PREV
+	@\$(call echo_message, Building)
+	@./progress_bar.sh \$@ \$\$PPID &
+	@echo -e "\n\`date\`\n\nKB: \`du -skx --exclude=\$(SCRIPT_ROOT) / \`\n" >logs/$LOGFILE
+EOF
+) >> $MKFILE.tmp
+}
+
+
+#----------------------------------#
+CHROOT_Unpack() {                  #
 #----------------------------------#
   local FILE=$1
   local optSAVE_PREVIOUS=$2
@@ -234,20 +254,46 @@ EOF
 }
 
 
-unset wrt_remove_build_dirs
 #----------------------------------#
-wrt_remove_build_dirs() {          #
+CHROOT_wrt_test_log() {            #
 #----------------------------------#
-  local name=$1
+  local TESTLOGFILE=$1
 (
-cat << EOF
-	@\$(call remove_build_dirs,$name)
+cat  << EOF
+	@echo "export TEST_LOG=/\$(SCRIPT_ROOT)/test-logs/$TESTLOGFILE" >> envars && \\
+	echo -e "\n\`date\`\n" >test-logs/$TESTLOGFILE
 EOF
 ) >> $MKFILE.tmp
 }
 
+
 #----------------------------------#
-wrt_remove_build_dirs2() {         #
+CHROOT_wrt_RunAsRoot() {           #
+#----------------------------------#
+  local file=$1
+(
+cat << EOF
+	@( time { source envars && \$(crCMDSDIR)/$file >>logs/$this_script 2>&1 ; } ) 2>>logs/$this_script && \\
+	\$(PRT_DU_CR) >>logs/$this_script
+EOF
+) >> $MKFILE.tmp
+
+}
+
+
+#----------------------------------#
+CHROOT_wrt_CopyFstab() {           #
+#----------------------------------#
+(
+cat << EOF
+	@( time { cp -v /sources/fstab /etc/fstab >>logs/${this_script} 2>&1 ; } ) 2>>logs/${this_script}
+EOF
+) >> $MKFILE.tmp
+}
+
+
+#----------------------------------#
+CHROOT_wrt_RemoveBuildDirs() {     #
 #----------------------------------#
   local name=$1
 (
@@ -256,7 +302,6 @@ cat << EOF
 EOF
 ) >> $MKFILE.tmp
 }
-
 
 
 unset wrt_touch
@@ -270,128 +315,73 @@ EOF
 ) >> $MKFILE.tmp
 }
 
-unset wrt_RunAsUser
-#----------------------------------#
-wrt_RunAsUser() {                  # Execute script inside time { }, footer to log file
-#----------------------------------#
-  local this_script=$1
-  local file=$2
 
-(
-cat << EOF
-	@( time { \$(SU_LUSER) "source \$(LUSER_HOME)/.bashrc && \$(CMDSDIR)/`dirname $file`/\$@" >> logs/\$@ 2>&1; } ) 2>> logs/\$@ && \\
-	\$(PRT_DU) >> logs/\$@
-EOF
-) >> $MKFILE.tmp
+#----------------------------------#
+wrt_blfs_tool_targets() {          #
+#----------------------------------#
+
+  echo "${tab_}${GREEN}Processing... ${L_arrow}BLFS_TOOL ${R_arrow}"
+
+  for file in blfs-tool-deps/* ; do
+    # Keep the script file name
+    this_script=`basename $file`
+
+    # Grab the name of the target
+    name=`echo ${this_script} | sed -e 's@[0-9]\{3\}-@@'`
+
+    # Find the package.
+    case $name in
+      tidy )  pkg_tarball=${TIDY_PKG} ;;
+      unzip ) pkg_tarball=${UNZIP_PKG} ;;
+      * )     pkg_tarball=$(get_package_tarball_name $name) ;;
+    esac
+
+    # Append each name of the script files to a list (this will become
+    # the names of the targets in the Makefile)
+    blfs_tool="$blfs_tool ${this_script}"
+
+    #--------------------------------------------------------------------#
+    #         >>>>>>>> START BUILDING A Makefile ENTRY <<<<<<<<          #
+    #--------------------------------------------------------------------#
+    #
+    # Drop in the name of the target on a new line, and the previous target
+    # as a dependency. Also call the echo_message function.
+    CHROOT_wrt_target "${this_script}" "$PREV"
+
+    # Insert instructions for unpacking the package and changing directories
+    # DocBook-XML is a zip, the build script will handle that.
+    [[ ! "$name" = "docbook-xml" ]] && CHROOT_Unpack "$pkg_tarball"
+
+    # Run the script.
+    CHROOT_wrt_RunAsRoot "$file"
+
+    # Remove the build directory(ies) except if the package build fails.
+    [[ ! "$name" = "docbook-xml" ]] && CHROOT_wrt_RemoveBuildDirs "$name"
+
+    # Touch the tracking file.
+    case $name in
+      tidy )  pkg_ver=tidy-051026 ;;
+      unzip ) pkg_ver=unzip-5.52 ;;
+      * )     pkg_ver=$(echo $pkg_tarball | sed -e 's/.tar.*//;s/.tgz//;s/.zip//') ;;
+    esac
+    echo -e "\t@touch $TRACKING_DIR/$pkg_ver" >>  $MKFILE.tmp
+
+    # Include a touch of the target name so make can check
+    # if it's already been made.
+    wrt_touch
+    #
+    #--------------------------------------------------------------------#
+    #              >>>>>>>> END OF Makefile ENTRY <<<<<<<<               #
+    #--------------------------------------------------------------------#
+
+    # Keep the script file name for Makefile dependencies.
+    PREV=${this_script}
+  done
 }
 
-
-#----------------------------------#
-wrt_RunAsRoot() {                  # Some scripts must be run as root..
-#----------------------------------#
-  local ENV_MOUNT
-  local this_script=$1
-  local file=$2
-
-  case ${PROGNAME} in
-    lfs   ) MOUNT_ENV="LFS" ;;
-    blfs  ) MOUNT_ENV="BLFS" ;;
-    clfs  ) MOUNT_ENV="CLFS" ;;
-    clfs2 ) MOUNT_ENV="CLFS" ;;
-    hlfs  ) MOUNT_ENV="HLFS" ;;
-    *) echo "undefined progname $PROGNAME"; exit 1
-  esac
-
-(
-cat << EOF
-	@( time { export ${MOUNT_ENV}=\$(MOUNT_PT) && ${PROGNAME}-commands/`dirname $file`/\$@ >>logs/\$@ 2>&1 ; } ) 2>>logs/\$@ && \\
-	\$(PRT_DU_CR) >>logs/\$@
-EOF
-) >> $MKFILE.tmp
-}
-
-#----------------------------------#
-wrt_run_as_root2() {               #
-#----------------------------------#
-  local this_script=$1
-  local file=$2
-(
-cat << EOF
-	@( time { source envars && ${PROGNAME}-commands/`dirname $file`/\$@ >>logs/\$@ 2>&1 ; } ) 2>>logs/\$@ && \\
-	echo -e "\nKB: \`du -skx --exclude=${SCRIPT_ROOT} \`\n" >>logs/\$@
-EOF
-) >> $MKFILE.tmp
-}
-
-
-unset wrt_run_as_chroot1
-#----------------------------------#
-wrt_run_as_chroot1() {             #
-#----------------------------------#
-  local this_script=$1
-  local file=$2
-(
-cat << EOF
-	@( time { \$(CHROOT1) 'cd \$(SCRIPT_ROOT) && source envars && \$(crCMDSDIR)/$file >>logs/${this_script} 2>&1' ; } ) 2>>logs/${this_script} && \\
-	\$(PRT_DU_CR) >> logs/${this_script}
-EOF
-) >> $MKFILE.tmp
-}
-
-unset wrt_run_as_chroot2
-#----------------------------------#
-wrt_run_as_chroot2() {             #
-#----------------------------------#
-  local this_script=$1
-  local file=$2
-(
-cat << EOF
-	@( time { \$(CHROOT2) 'cd \$(SCRIPT_ROOT) && source envars && \$(crCMDSDIR)/`dirname $file`/\$@ >>logs/\$@ 2>&1' ; } ) 2>>logs/\$@ && \\
-	\$(PRT_DU_CR) >> logs/\$@
-EOF
-) >> $MKFILE.tmp
-}
-
-unset wrt_target
-#----------------------------------#
-wrt_target() {                     # Create target and initialize log file
-#----------------------------------#
-  local i=$1
-  local PREV=$2
-  case $i in
-    iteration* ) local LOGFILE="\$@.log" ;;
-             * ) local LOGFILE="\$@"     ;;
-  esac
-(
-cat << EOF
-
-$i:  $PREV
-	@\$(call echo_message, Building)
-	@./progress_bar.sh \$@ \$\$PPID &
-	@echo -e "\n\`date\`\n\nKB: \`du -skx --exclude=${SCRIPT_ROOT} \$(MOUNT_PT)\`\n" >logs/$LOGFILE
-EOF
-) >> $MKFILE.tmp
-}
-
-#----------------------------------#
-wrt_target_boot() {                # Create target and initialize log file
-#----------------------------------#
-  local i=$1
-  local PREV=$2
-  case $i in
-    iteration* ) local LOGFILE="\$@.log" ;;
-             * ) local LOGFILE="\$@" ;;
-  esac
-(
-cat << EOF
-
-$i:  $PREV
-	@\$(call echo_message, Building)
-	@./progress_bar.sh \$@ \$\$PPID &
-	@echo -e "\n\`date\`\n\nKB: \`du -skx --exclude=${SCRIPT_ROOT}\`\n" >logs/$LOGFILE
-EOF
-) >> $MKFILE.tmp
-}
+#------------------------------------------------------#
+#        END Makefile scripting functions              #
+#------------------------------------------------------#
 
 
 
@@ -401,8 +391,8 @@ run_make() {                 #
   # Test if make must be run.
   if [ "$RUNMAKE" = "y" ] ; then
     # Test to make sure we're running the build as root
-    if [ "$UID" != "0" ] ; then
-      echo "You must be logged in as root to successfully build the system."
+    if [ "$UID" = "0" ] ; then
+      echo "You must not be logged in as root to build the system."
       exit 1
     fi
     # Build the system
@@ -427,7 +417,7 @@ clean_builddir() {           #
     fi
     # Test to make sure that the build directory was populated by jhalfs
     if [ ! -d $JHALFSDIR ] || [ ! -d $BUILDDIR/sources ] ; then
-      echo "Looks like $BUILDDIR was not populated by a previous jhalfs run."
+      echo "Looks like $BUILDDIR was not populated by a previous jhalfs-X run."
       exit 1
     else
       # Clean the build directory
@@ -586,6 +576,7 @@ extract_commands() {         #
 
   # Done. Moving on...
   get_sources
+
 }
 
 #----------------------------#
@@ -615,6 +606,9 @@ create_package_list() {      #
 cat << EOF
 $LIBXML_PKG
 $LIBXSLT_PKG
+$TIDY_PKG
+$UNZIP_PKG
+$DBXML_PKG
 $DBXSL_PKG
 $LINKS_PKG
 $SUDO_PKG
@@ -799,6 +793,7 @@ create_urls() {              #
   if [[ "${BLFS_TOOL}" = "y" ]]; then
     add_blfs_deps_urls
   fi
+
 }
 
 #----------------------------# Hardcoded URLs and MD5.
@@ -813,6 +808,19 @@ add_blfs_deps_urls() {       # No easy way to extract it.
 
   if [[ "${DEP_LIBXSLT}" = "y" ]] ; then
     echo "${LIBXSLT_URL} ${BLFS_SERVER}libxslt/${LIBXSLT_PKG} ${LIBXSLT_MD5}" >> urls.lst
+  fi
+
+  if [[ "${DEP_TIDY}" = "y" ]] ; then
+    echo "${TIDY_URL} ${BLFS_SERVER}tidy/${TIDY_PKG} ${TIDY_MD5}" >> urls.lst
+    echo "${TIDY_PATCH_URL} ${BLFS_SERVER}tidy/${TIDY_PATCH} ${TIDY_PATCH_MD5}" >> urls.lst
+  fi
+
+  if [[ "${DEP_UNZIP}" = "y" ]] ; then
+    echo "${UNZIP_URL} ${BLFS_SERVER}unzip/${UNZIP_PKG} ${UNZIP_MD5}" >> urls.lst
+  fi
+
+  if [[ "${DEP_DBXML}" = "y" ]] ; then
+    echo "${DBXML_URL} ${BLFS_SERVER}docbook-xml/${DBXML_PKG} ${DBXML_MD5}" >> urls.lst
   fi
 
   if [[ "${DEP_DBXSL}" = "y" ]] ; then
@@ -858,28 +866,40 @@ copy_blfs_deps_scripts() {   # method avoid to place the test on all
     mv blfs-tool-deps/902-libxslt ${PROGNAME}-commands/blfs-tool-deps
   fi
 
+  if [[ "${DEP_TIDY}" = "y" ]] ; then
+    mv blfs-tool-deps/903-tidy ${PROGNAME}-commands/blfs-tool-deps
+  fi
+
+  if [[ "${DEP_UNZIP}" = "y" ]] ; then
+    mv blfs-tool-deps/904-unzip ${PROGNAME}-commands/blfs-tool-deps
+  fi
+
+  if [[ "${DEP_DBXML}" = "y" ]] ; then
+    mv blfs-tool-deps/905-docbook-xml ${PROGNAME}-commands/blfs-tool-deps
+  fi
+
   if [[ "${DEP_DBXSL}" = "y" ]] ; then
-    mv blfs-tool-deps/903-docbook-xsl ${PROGNAME}-commands/blfs-tool-deps
+    mv blfs-tool-deps/906-docbook-xsl ${PROGNAME}-commands/blfs-tool-deps
   fi
 
   if [[ "${DEP_LINKS}" = "y" ]] ; then
-    mv blfs-tool-deps/905-links ${PROGNAME}-commands/blfs-tool-deps
+    mv blfs-tool-deps/908-links ${PROGNAME}-commands/blfs-tool-deps
   fi
 
   if [[ "${DEP_SUDO}" = "y" ]] ; then
-    mv blfs-tool-deps/906-sudo ${PROGNAME}-commands/blfs-tool-deps
+    mv blfs-tool-deps/909-sudo ${PROGNAME}-commands/blfs-tool-deps
   fi
 
   if [[ "${DEP_WGET}" = "y" ]] ; then
-    mv blfs-tool-deps/907-wget ${PROGNAME}-commands/blfs-tool-deps
+    mv blfs-tool-deps/910-wget ${PROGNAME}-commands/blfs-tool-deps
   fi
 
   if [[ "${DEP_SVN}" = "y" ]] ; then
-    mv blfs-tool-deps/908-subversion ${PROGNAME}-commands/blfs-tool-deps
+    mv blfs-tool-deps/911-subversion ${PROGNAME}-commands/blfs-tool-deps
   fi
 
   if [[ "${DEP_GPM}" = "y" ]] ; then
-    mv blfs-tool-deps/904-gpm ${PROGNAME}-commands/blfs-tool-deps
+    mv blfs-tool-deps/907-gpm ${PROGNAME}-commands/blfs-tool-deps
   fi
 
   rm -rf blfs-tool-deps
